# Generated by Django 5.0.6 on 2026-03-13 17:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorridaAnalitica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('OK', 'OK'), ('ERROR', 'Error')], max_length=10)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('registros_procesados', models.PositiveIntegerField(default=0)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Corrida analítica',
                'verbose_name_plural': 'Corridas analíticas',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
        migrations.CreateModel(
            name='HechoConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_movimiento', models.CharField(max_length=3)),
                ('cantidad_total', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hechos_consumo', to='products.producto')),
            ],
            options={
                'verbose_name': 'Hecho de consumo',
                'verbose_name_plural': 'Hechos de consumo',
                'ordering': ['-fecha', 'producto', 'tipo_movimiento'],
                'unique_together': {('producto', 'fecha', 'tipo_movimiento')},
            },
        ),
    ]
