# Generated by Django 5.0.6 on 2026-03-13 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenConsumoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('cantidad_salidas', models.IntegerField(default=0)),
                ('promedio_diario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dias_con_movimiento', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_consumo', to='products.producto')),
            ],
            options={
                'verbose_name': 'Resumen consumo mensual',
                'verbose_name_plural': 'Resúmenes consumo mensual',
                'ordering': ['-anio', '-mes', 'producto'],
                'unique_together': {('producto', 'anio', 'mes')},
            },
        ),
    ]
