# Generated by Django 5.2.12 on 2026-04-25 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_resumen_consumo_mensual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='corridaanalitica',
            name='ejecutado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corridas_analiticas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corridaanalitica',
            name='error_detalle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='corridaanalitica',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corridaanalitica',
            name='metodo',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled'), ('API', 'API'), ('RETRY', 'Retry')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='corridaanalitica',
            name='parametros',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='corridaanalitica',
            name='puntos_usados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corridaanalitica',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corridaanalitica',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corridaanalitica',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='corridaanalitica',
            name='estado',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('ERROR', 'Error'), ('CANCELLED', 'Cancelled'), ('OK', 'OK (Legacy)')], default='QUEUED', max_length=10),
        ),
    ]
