# Generated by Django 5.2.12 on 2026-04-26 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_corridaanalitica_ejecutado_por_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultadoTendenciaLineal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("variable_objetivo", models.CharField(max_length=100)),
                ("periodicidad", models.CharField(max_length=20)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("puntos_usados", models.PositiveIntegerField(default=0)),
                ("pendiente", models.DecimalField(decimal_places=6, max_digits=18)),
                ("intercepto", models.DecimalField(decimal_places=6, max_digits=18)),
                ("r2", models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ("mae", models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ("rmse", models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ("prediccion_siguiente", models.DecimalField(decimal_places=6, max_digits=18)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "corrida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_tendencia",
                        to="analytics.corridaanalitica",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_tendencia",
                        to="products.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de tendencia lineal",
                "verbose_name_plural": "Resultados de tendencia lineal",
                "ordering": ["-corrida__fecha_ejecucion", "producto_id"],
            },
        ),
    ]
