# Generated by Django 5.0.6 on 2026-03-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudinsumo',
            name='motivo_rechazo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
