# Generated by Django 5.2.12 on 2026-04-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_solicituddetalle_insumo_fuera_catalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddetalle',
            name='descripcion_insumo_solicitado',
            field=models.CharField(blank=True, default='', help_text='Insumo pedido fuera de catálogo hasta que Compras cree el producto y vincule.', max_length=500),
        ),
    ]
