# Generated by Django 5.2.12 on 2026-06-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_solicituddetalle_cantidad_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddetalle',
            name='cantidad_inicial',
            field=models.PositiveIntegerField(help_text='Cantidad pedida por el funcionario al crear la solicitud (no se modifica).'),
        ),
    ]
