# Generated by Django 5.2.12 on 2026-04-25 20:51

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sync_superuser_roles'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.SegupakUserManager()),
            ],
        ),
    ]
