# Generated by Django 5.2.12 on 2026-06-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_producto_sku_blank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['id'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
