# Generated by Django 6.0.1 on 2026-02-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_solicitudcompraitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='cantidad_texto',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='destino_producto',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='firma_encargado',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='marca_recomendada',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='medidas',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='proveedor_recomendado',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='tamano',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='tipo_producto',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
